openapi: 3.0.0
info:
  version: 1.0.0
  title: 头版新闻
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://www.openapis.org/wp-content/uploads/sites/3/2018/02/OpenAPI_Logo_Pantone-1.png'
  description: |
    头版新闻服务的 API 文档
tags:
  - name: Type
    description: 新闻栏目相关
  - name: List
    description: 新闻列表相关
servers:
  - url: 'http://139.198.15.19:8080'
paths:
  /news/type:
    get:
      tags:
        - Type
      summary: 获取新闻栏目
      operationId: getNewsType
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    description: 返回的状态，成功为true，出现错误为 false
                    type: boolean
                    example: true
                  msg:
                    description: 错误消息，成功为""，出现错误则为错误信息
                    type: string
                    example: ''
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Type'
  /news/list:
    get:
      parameters:
        - name: id
          required: false
          in: query
          description: 新闻栏目 id，不指定则返回头条栏目的新闻
          schema:
            type: integer
            example: 1
        - name: index
          required: false
          in: query
          description: 新闻列表的页面编号(第一页编号为0)，不指定则返回全部新闻
          schema:
            type: integer
            example: 1
      tags:
        - List
      summary: 获取新闻列表
      operationId: getNewsList
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    description: 返回的状态，成功为true，出现错误为 false
                    type: boolean
                    example: true
                  msg:
                    description: 错误消息，成功为""，出现错误则为错误信息
                    type: string
                    example: index overflow
                  totalCount:
                    description: 当前刷新的新闻总条数
                    type: integer
                    example: 30
                  data:
                    $ref: '#/components/schemas/List'
components:
  schemas:
    Type:
      type: object
      required:
        - id
        - title
        - order
      properties:
        id:
          description: 栏目 id
          type: integer
          example: 1
        title:
          description: 栏目标题
          type: string
          example: 头条
        order:
          description: 栏目次序编号
          type: integer
          example: 1
    List:
      type: array
      items:
        type: object
        required:
          - uniquekey
          - title
          - date
          - author_name
          - url
        properties:
          uniquekey:
            description: 新闻条目的全局唯一key
            type: string
            example: f27589a0ea4ff36cdfc8b4b03693bbde
          title:
            description: 新闻条目的标题
            type: string
            example: 王中王！德约一稳定江山，大满贯稳步追赶或成最终赢家
          date:
            description: '新闻条目的发表时间，格式为"yyyy-MM-dd HH:mm"'
            type: string
            format: date-time
            example: '2019-07-15 10:50'
          author_name:
            description: 新闻条目的来源
            type: string
            example: 胖哥体育
          url:
            description: 新闻条目的详情页面的完整 url
            type: string
            format: url
            example: 'http://mini.eastday.com/mobile/190715105025650.html'
          thumbnail_pic_s:
            description: 新闻条目的缩略图1的相对路径，需要和 baseURL 拼接
            type: string
            example: 20190715105025_878317e185cc8776106d73d76be366c6_3_mwpm_03200403.jpg
          thumbnail_pic_s02:
            description: 新闻条目的缩略图1的相对路径，需要和 baseURL 拼接
            type: string
            example: 20190715105025_878317e185cc8776106d73d76be366c6_2_mwpm_03200403.jpg
          thumbnail_pic_s03:
            description: 新闻条目的缩略图1的相对路径，需要和 baseURL 拼接
            type: string
            example: 20190715105025_878317e185cc8776106d73d76be366c6_1_mwpm_03200403.jpg
