name: Node CI

on:
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Config git
      run: |
        git config --local user.email "qinyusuain@gmail.com"
        git config --local user.name "qinyu"

    - name: Publish github pages
      run: |
        echo ${{ secrets.ACCESS_TOKEN }}
        npm install
        npm run build
        npm test
        npm run gh-pages
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
