name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
        npm run ghpages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
